### ISSUE TITLE
'Archival Storage' and 'Appraisal' tabs present after Ubuntu 16.04 install

### ISSUE THREAD

**Issue by jpellman** [artefactual/archivematica-docs#154] opened 2018-05-04 14:58 UTC
Version of the documentation: 1.7

Page (and section, if applicable) where the issue occurs: [Ubuntu installation instructions](https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation-setup/installation/install-ubuntu/#install-pkg-ubuntu), step 12

Description of the issue: After performing a fresh install of Archivematica 1.7 with Elasticsearch disabled on Ubuntu 16.04, we noticed that the 'Archival Storage' and 'Appraisal' tabs are still present in the dashboard despite Elasticsearch not being active.  This behavior does not occur in CentOS 7 after a fresh install, where these tabs are missing as expected.  Performing a reboot of the Ubuntu host fixes this error.  This implies that the `archivematica-mcp-server`, `archivematica-mcp-client`, and `archivematica-dashboard` services are loaded in a different order by systemd than they are in step 12, and that similarly in the [CentOS 7 instructions](https://www.archivematica.org/en/docs/archivematica-1.7/admin-manual/installation-setup/installation/install-centos/#install-pkg-centos) under step 6 the services are also loaded in a different order.  In fact, for CentOS 7, the services are loaded as follows in step 6:

1. `archivematica-mcp-client`
2. `archivematica-dashboard`
3. `archivematica-mcp-server`

And for Ubuntu 16.04 they are loaded in the following order in step 12:

1. `archivematica-mcp-server`
2. `archivematica-mcp-client`
3. `archivematica-dashboard`

It seems that the Ubuntu 16.04 instructions would want to use the same ordering as CentOS 7 for this to work as expected.

**Comment by kellyannewithane** [comment] 2018-05-04 17:58
@jpellman seems that the issue isn't with the order the services are loaded but rather that we need to restart mcp-client and archivematica-dashboard instead of starting them.  This is now fixed in the documentation.

**Closed** 2018-08-22 22:26 UTC
Labels: CUL: phase 1, Columbia University Library, Status: review
